jobs:
  include:
    - language: go
      go: 1.11.x
      before_script: cd cloud-function/
      script: go test -v -timeout 30s -tags testing ./...

    - language: node_js
      node_js: "lts/*"
      install:
        - npm install -g mocha@"^3.5.3"
        - npm install chai@"3.5.0" jsonschema@"^1.1.1"
        - npm install convert-units@"^2.1.0"
        - npm install image-size@"^0.6.3"
      script: mocha
